### ISSUE TITLE
Client Origin and Referer

### ISSUE THREAD

**Issue by djordjedjukic** [serilog-contrib/serilog-enrichers-clientinfo#18]
I needed those two properties in enriched.

Do you mind if I make PR to your library with those 2?

**Comment by mo-esmp** [comment]
@djordjedjukic Sure, why not!

**Comment by mo-esmp** [comment]
This can be closed, hence any request header can be logged by `WithRequestHeader("Header-Name1")` enricher. Feel free to reopen
