### ISSUE TITLE
IPv6 address ClientIp not properly parsed from X-forwarded-for header

### ISSUE THREAD

**Issue by mraz1337** [serilog-contrib/serilog-enrichers-clientinfo#19]
I noticed in logs that ipv6 addresses are truncated. e.g.  **2001:4860:7:505:** 

Looks like [this](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/blob/master/src/Serilog.Enrichers.ClientInfo/Enrichers/ClientIpEnricher.cs#L90) code doesn't respect rules from [RFC7239](https://www.rfc-editor.org/rfc/rfc7239)

**Comment by mo-esmp** [comment]
Thanks for reporting this issue and will check soon.
