### ISSUE TITLE
X-forwarded-for and CF-Connecting-IP

### ISSUE THREAD

**Issue by CrAcK75** [serilog-contrib/serilog-enrichers-clientinfo#21]
Sorry in advance if I wrote something wrong but... is it possible to use both X-forwarded-for and CF-Connecting-IP or others?
something like 
```
"Args": {
          "xForwardHeaderName": [ "CF-Connecting-IP", "X-Forwarded-For", "X-Real-IP" ]
        }
```

**Comment by mo-esmp** [comment]
Unfortunately, it is not possible, however, this might help (as a workaround) but I'm not sure:
- Update package to version 2.0.0
- Use `WithRequestHeader` enricher
```json
{
  "Serilog": {
    "MinimumLevel": "Debug",
    "Using":  [ "Serilog.Enrichers.ClientInfo" ],
    "Enrich": [ 
      {
        "Name": "WithClientIp",
        "Args": {
          "headerName": "CF-Connecting-IP"
        }
      },
      {
        "Name": "WithRequestHeader",
        "Args": {
          "headerName": "X-Forwarded-For"
        }
      },
      {
        "Name": "WithRequestHeader",
        "Args": {
          "headerName": "X-Real-IP"
        }
      }
    ],
  }
}
```

**Comment by CrAcK75** [comment]
It work's but I lose che WithClientAgent info now, the appsettings is:

    "Enrich": [
      "WithClientAgent",
      
      i try also with:
      
            {
            "Name": "WithClientAgent",
            "Args": {
              "headerName": "User-Agent"
            }
      },
      
but the ClientAgent info disappeared

**Comment by CrAcK75** [comment]
it's all right now, thank you
