### ISSUE TITLE
ClientAgent replacement not working

### ISSUE THREAD

**Issue by Su-s** [serilog-contrib/serilog-enrichers-clientinfo#23]
Hi this is my serilog configuration in app.settings.json

```

{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File",
      "Serilog.Sinks.Seq",
      "Serilog.Enrichers.ClientInfo",
      "Serilog.Enrichers.CorrelationId",
      "Serilog.Enrichers.ExceptionStackTraceHash",
      "Serilog.Enrichers.Environment",
      "Serilog.Enrichers.Memory"
    ],
    "MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft.AspNetCore": "Warning",
        "Microsoft": "Information",
        "Microsoft.EntityFrameworkCore.Database.Command": "Error",
        "Microsoft.AspNetCore.SignalR": "Information",
        "Microsoft.AspNetCore.Http.Connections": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [correlationId: {CorrelationId} machineName:{MachineName} environmentName:{EnvironmentName} environmentUserName:{EnvironmentUserName} clientIp:{ClientIp} requestHeader:{RequestHeader} processId:{ProcessId} processName:{ProcessName} memory:{MemoryUsage} level:{Level: u3}] ({SourceContext}) {Message} {NewLine} {Exception} {NewLine}",
          "theme": "Serilog.Sinks.SystemConsole.Themes.Literate",
          "restrictedToMinimumLevel": "Information"
        }
      },
      {
        "Name": "Seq",
        "Args": {
          "serverUrl": "http://localhost:5341/",
          "apiKey": "none",
          "restrictedToMinimumLevel": "Information"
        }
      },
      {
        "Name": "File",
        "Args": {
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [correlationId: {CorrelationId} machineName:{MachineName} environmentName:{EnvironmentName} environmentUserName:{EnvironmentUserName} clientIp:{ClientIp} requestHeader:{RequestHeader} processId:{ProcessId} processName:{ProcessName} memory:{MemoryUsage} level:{Level: u3}] ({SourceContext}) {Message} {NewLine} {Exception} {NewLine}",
          "path": "C:\\Users\\Lenovo\\AppData\\Local\\Logs\\Cloud.log",
          "rollingInterval": "Day",
          "restrictedToMinimumLevel": "Verbose"
        }
      }
    ],
    "Enrich": [
      "FromLogContext",
      "WithMachineName",
      {
        "Name": "WithClientIp",
        "Args": {
          "headerName": "CF-Connecting-IP"
        }
      },
      {
        "Name": "WithRequestHeader",
        "Args": {
          "headerName": "User-Agent"
        }
      },
      "WithMessageTemplate",
      "WithEnvironmentUserName",
      "WithMemoryUsage",
      "WithEnvironmentName",
      "WithExceptionDetails",
      "ExceptionStackTraceHash",
      "WithExceptionProperties",
      "WithProcessName",
      "WithProcessId"
    ]
  }
}

```
 I have updated the client agent to request header according to the enricher package change. But now, im not able to display the client agent details in log.
 
 
 
![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/37269911/4b758dd6-d64b-4dc3-9295-7e142b136d61)
![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/37269911/4d6ac216-5bc2-473c-ae73-6803f639d7f4)

Please help me to fix the issue

**Comment by mo-esmp** [comment]
@Su-s please replace `requestHeader:{RequestHeader}` with `clientAgent:{UserAgent}` and let me know the result.


![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/1659032/40c2dd39-7e10-465c-8148-3387e8a5a1df)

**Comment by Su-s** [comment]
Ok

**Comment by Su-s** [comment]
> @Su-s please replace `requestHeader:{RequestHeader}` with `clientAgent:{UserAgent}` and let me know the result.
> 
> 
> ![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/1659032/40c2dd39-7e10-465c-8148-3387e8a5a1df)
> 

Ok

**Comment by Su-s** [comment]
![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/37269911/1f557ee3-cb41-4dc2-9eea-80738abcc542)

by keeping the changes in the enriched, correct?


now also the log did not changed

![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/37269911/2912fa50-73f1-4978-85f6-6fd5f6152ec9)


also the serilog is not showing  the clientagent details in seq

![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/37269911/8408f5f7-1ef6-4114-a18f-a2b24d30c75c)

**Comment by mo-esmp** [comment]
I added a [sample project](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/tree/master/sample/SampleWebApp). Check the branch and see if it is working, use the enricher configuration in the `appsettings.json` file.

**Comment by Su-s** [comment]
![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/37269911/a83b9599-2319-47ad-a911-84349da17e57)
 the agent and correlation id are working with your sample code. 



![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/37269911/3307455a-6662-464a-b0af-9fd94d17eff1)

but I had updated the code slightly so that it match with the settings in my application, and found that the after applying the change to set the log level no logs were displaying after the application start

`"MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft.AspNetCore": "Warning",
        "Microsoft": "Information",
        "Microsoft.EntityFrameworkCore.Database.Command": "Error",
        "Microsoft.AspNetCore.SignalR": "Information",
        "Microsoft.AspNetCore.Http.Connections": "Information"
      }
    },`

**Comment by mo-esmp** [comment]
When you run your application for the first time (application startup), these fields are null and when client sends request to your application, they should have values.

**Comment by Su-s** [comment]
yes, understood that. i have updated the serilog wrodaroud app to make the changes work

https://github.com/Su-s/serilogworkaround/commit/d5673b0206d20de17c19ceb5c6b54fa01f5885bc

could you please take a look and suggest me the changes.

when i did the sample without additional configuration, just like the code in your sample app, there were no issues. but its not working as expected, like as before. even after adding the changes you mentioned in the sample app

**Comment by Su-s** [comment]
![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/37269911/9968aa5c-84c0-4b87-acd9-c0b4cac92ecd)
when i try to debug the httpcontext become null, please check the image

**Comment by mo-esmp** [comment]
I've added `builder.Services.AddHttpContextAccessor();` to your code and it fixed the problem.
![image](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/assets/1659032/1c8f772e-9258-4ba4-a80d-1b978ea9084b)

**Comment by Su-s** [comment]
Thanks for the help made it work!

**Comment by Su-s** [comment]
Thanks for the help made it work!

Fully working example  

https://github.com/Su-s/serilogworkaround
