### ISSUE TITLE
Dependency on deprecated package

### ISSUE THREAD

**Issue by cremor** [serilog-contrib/serilog-enrichers-clientinfo#24]
Installing this package results in a transitive dependency on the deprecated package `Microsoft.AspNetCore.Http`. Please fix this so that the deprecated package is not referenced any more.

I assume this can be done similar to how Serilog.AspNetCore does it: https://github.com/serilog/serilog-aspnetcore/blob/e6e51d8f64f50833bb539734816a91d5efd669b4/src/Serilog.AspNetCore/Serilog.AspNetCore.csproj#L40-L48

**Comment by mo-esmp** [comment]
Hey @cremor,
Thanks for the reporting; it would be nice if you sent a PR to fix this.

**Comment by cremor** [comment]
@edmacdonald just created a PR: #31
