### ISSUE TITLE
Passing correlation id to HttpClient

### ISSUE THREAD

**Issue by sergiojrdotnet** [serilog-contrib/serilog-enrichers-clientinfo#28]
Is there any suggestion about how can I get and pass the current correlation id through `HttpClient`'s from `HttpClientFactory`?
My objective is to propagate the current value to subsequent microservices.

**Comment by mo-esmp** [comment]
Correlation id would be [cached in HttpContext.Items](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/blob/241329538870099dbd2c36eb4eb43de55f5fb484/src/Serilog.Enrichers.ClientInfo/Enrichers/CorrelationIdEnricher.cs#L44) as [LogEventProperty](https://github.com/serilog-contrib/serilog-enrichers-clientinfo/blob/241329538870099dbd2c36eb4eb43de55f5fb484/test/Serilog.Enrichers.ClientInfo.Tests/CorrelationIdEnricherTests.cs#L42C37-L42C94) and you can use it to get value.
```csharp
var logEventProperty =  HttpContext.Items["CorrelationId"] as LogEventProperty;
var correlationId = logEventProperty.Properties["CorrelationId"].LiteralValue().ToString();
```
